import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Navbar from "@/components/navbar";
import { ToastContainer } from "react-toastify";

// Importación de fuentes y estilos globales
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configuración de metadatos de la aplicación
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente principal que define la estructura base de la aplicación
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" />
        <title>Tasks inlaze</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="container">

          <SessionAuthProvider>
            <Navbar />
            {children}
          </SessionAuthProvider>
        </main>
        <ToastContainer />
      </body>
    </html>
  );
}
